import { awardSlots, awardWallSlots } from "./imageSlots";
import type { ImageSlot } from "./imageSlots";

/**
 * The fourteen awards standing on the shelves of the About photograph.
 *
 * Two things are authored here, and neither can be derived from the files.
 *
 * The first is where each trophy stands, as a percentage of `aboutBand.webp`.
 * Because the band keeps the plate's 1920x800 ratio, a percentage lands on the
 * same trophy at every width and every zoom.
 *
 * These numbers are generated by `tools/build-award-wall.mjs`, which matches
 * each cut-out against the band rather than guessing at its edges. That matters
 * because the wall lays a trophy's own cut-out over the trophy baked into the
 * photograph: a few pixels out and it ghosts against itself. Scanning for the
 * gold and black of a frame edge was tried first and produced boxes 15% to
 * 118% away from the cut-outs' own aspect ratios, because the scan picks up
 * neighbouring frames and the shadow under the shelf. The match scores in the
 * comments are the mean channel difference over each cut-out's opaque pixels,
 * on a 0-255 scale; they bottom out near 10 rather than at 0 because the band
 * and the cut-outs were WebP-encoded separately. Re-run the tool after any
 * re-encode of either.
 *
 * The second is the copy. Names and years come off the delivered filenames,
 * but the issuing body of an award is a claim, so only SME100 is named: it is
 * the one programme in the set whose criteria are on public record. The other
 * thirteen summaries say what the recognition is for and stop there, because
 * inventing an organiser would invent a credential.
 */
export type Award = {
  /** Dialog size. */
  slot: ImageSlot;
  /** Wall size, laid over the trophy standing in the band. */
  wallSlot: ImageSlot;
  name: string;
  year: string;
  summary: string;
  /* Percentages of the band. `top` and `height` come from the shelf. */
  left: number;
  width: number;
  top: number;
  height: number;
};

/* Generated by tools/build-award-wall.mjs. Do not hand-edit: re-run it. */
const PLACES = [
  { left: 57.03, width: 3.96, top: 20.75, height: 14.25 }, /* rising star, match 9.6 */
  { left: 62.08, width: 5.21, top: 21.50, height: 13.38 }, /* excellence, match 9.3 */
  { left: 68.59, width: 5.10, top: 21.63, height: 13.25 }, /* top 100 sme, match 9.0 */
  { left: 74.74, width: 4.22, top: 20.38, height: 14.63 }, /* sme100, match 8.1 */
  { left: 79.90, width: 5.31, top: 21.63, height: 13.38 }, /* e-commerce, match 10.5 */
  { left: 86.56, width: 3.54, top: 20.88, height: 14.12 }, /* brand impact, match 9.6 */
  { left: 91.20, width: 5.21, top: 21.88, height: 13.13 }, /* trusted brand, match 7.7 */
  { left: 57.03, width: 5.68, top: 53.50, height: 13.38 }, /* top merchant, match 9.0 */
  { left: 64.22, width: 2.60, top: 52.88, height: 13.88 }, /* top 3 live, match 11.1 */
  { left: 68.07, width: 5.31, top: 53.63, height: 13.25 }, /* top growth, match 8.8 */
  { left: 74.53, width: 4.48, top: 53.75, height: 13.25 }, /* million ringgit, match 10.9 */
  { left: 80.26, width: 5.42, top: 53.75, height: 13.13 }, /* best live, match 10.4 */
  { left: 86.82, width: 2.86, top: 54.37, height: 12.63 }, /* live excellence, match 10.7 */
  { left: 90.99, width: 5.42, top: 53.37, height: 13.50 }, /* preferred partner, match 9.9 */
];

const RECORDS: { id: string; name: string; year: string; summary: string }[] = [
  {
    id: "risingStarBrand2022",
    name: "Rising Star Brand",
    year: "2022",
    summary:
      "An early recognition of KIYO as a fast-rising brand, given for the commercial momentum built in its first years of trading.",
  },
  {
    id: "excellenceCustomerExperience2023",
    name: "Excellence in Customer Experience",
    year: "2023",
    summary:
      "For the standard of the buying experience end to end: how quickly enquiries are answered, how orders are handled, and how customers are looked after once a set has shipped.",
  },
  {
    id: "top100SmeMalaysia2023",
    name: "Top 100 SME Malaysia",
    year: "2023",
    summary:
      "Placement among Malaysia's leading hundred small and medium enterprises, assessed on trading performance rather than on profile.",
  },
  {
    id: "sme100FastMovingCompanies2023",
    name: "SME100 Awards, Fast Moving Companies",
    year: "2023",
    summary:
      "SME100 has ranked Malaysian SMEs since 2009. Scoring is 80% quantitative, on verified turnover, operating profit, growth and return on assets, and 20% qualitative, on management outlook, innovation and market presence.",
  },
  {
    id: "outstandingEcommerceAchievement2023",
    name: "Outstanding E-Commerce Achievement",
    year: "2023",
    summary:
      "For results achieved selling online: sales growth, campaign performance, and the day to day running of an e-commerce operation.",
  },
  {
    id: "brandImpactAward2024",
    name: "Brand Impact Award",
    year: "2024",
    summary:
      "A brand-impact recognition, given for the reach and recall a brand has built in the Malaysian market.",
  },
  {
    id: "malaysiaTrustedBrandAward2024",
    name: "Malaysia Trusted Brand Award",
    year: "2024",
    summary:
      "A trusted-brand recognition. Awards of this kind measure what buyers say about a brand rather than what the brand says about itself.",
  },
  {
    id: "tiktokShopTopMerchant2024",
    name: "TikTok Shop Top Merchant Award",
    year: "2024",
    summary:
      "A TikTok Shop merchant recognition, given for overall selling performance on the platform: creativity, customer engagement and leadership in a category.",
  },
  {
    id: "tiktokTop3LiveLuggageBrand2023",
    name: "TikTok Top 3 Live Luggage Brand",
    year: "2023",
    summary:
      "Third place among the luggage brands selling on TikTok LIVE in Malaysia that year. The ranking window and the measure behind it are TikTok's own.",
  },
  {
    id: "tiktokShopTopGrowthPartner2023",
    name: "TikTok Shop Top Growth Partner Award",
    year: "2023",
    summary:
      "For growth achieved inside the TikTok Shop ecosystem, and for the work done with the platform to reach it.",
  },
  {
    id: "millionRinggitSalesAchievement2023",
    name: "Million Ringgit Sales Achievement",
    year: "2023",
    summary:
      "A sales milestone, marking the point at which KIYO passed one million ringgit in recorded sales.",
  },
  {
    id: "bestLiveCommercePerformance2023",
    name: "Best Live Commerce Performance",
    year: "2023",
    summary:
      "For performance in livestream selling, judged on how a LIVE channel is run and on what it delivers.",
  },
  {
    id: "liveCommerceExcellenceAward2022",
    name: "Live Commerce Excellence Award",
    year: "2022",
    summary:
      "An early recognition in livestream commerce, from the years when live selling was still finding its feet in Malaysia.",
  },
  {
    id: "tiktokShopPreferredPartner2023",
    name: "TikTok Shop Preferred Partner",
    year: "2023",
    summary:
      "Preferred partner standing within the TikTok Shop ecosystem, held in 2023.",
  },
];

export const AWARDS: Award[] = RECORDS.map((record, index) => {
  const slot = awardSlots[record.id];
  const wallSlot = awardWallSlots[record.id];
  if (!slot || !wallSlot) throw new Error(`awardWall: no cut-out shipped for ${record.id}`);
  const place = PLACES[index];
  if (!place) throw new Error(`awardWall: no shelf position for ${record.id}`);

  return {
    ...record,
    ...place,
    /* Alt text belongs to the picture, and the picture is the trophy. The wall
       copy is decorative: it sits on top of the same trophy in the photograph
       and its button already carries the name. */
    slot: { ...slot, alt: `The ${record.name} ${record.year} trophy` },
    wallSlot,
  };
});
