/* Generated by tools/build-product-assets.mjs. Do not edit by hand. */

export type ProductColour = {
  id: string;
  label: string;
  swatch: string;
};

export type CarouselProduct = {
  slug: string;
  name: string;
  blurb: string;
  colours: ProductColour[];
};

/* Colours are pre-sorted: silver, black, white, then neutrals and chromatics.
   The first entry is the colour a product shows at rest. */
export const carouselProducts: CarouselProduct[] = [
  {
    "slug": "premium-aluminium-set",
    "name": "Premium Aluminium Set",
    "blurb": "Two-piece set with a front-opening cabin case",
    "colours": [
      {
        "id": "silver",
        "label": "Silver",
        "swatch": "#c6c7c7"
      },
      {
        "id": "black",
        "label": "Black",
        "swatch": "#272a27"
      },
      {
        "id": "blue",
        "label": "Blue",
        "swatch": "#afd3e0"
      },
      {
        "id": "green",
        "label": "Green",
        "swatch": "#bee0c4"
      },
      {
        "id": "pink",
        "label": "Pink",
        "swatch": "#efc3bb"
      }
    ]
  },
  {
    "slug": "full-spec-aluminium-frame",
    "name": "Full Spec Aluminium Frame",
    "blurb": "Aluminium frame, corner guards and TSA lock",
    "colours": [
      {
        "id": "black",
        "label": "Black",
        "swatch": "#2f2f2e"
      },
      {
        "id": "white",
        "label": "White",
        "swatch": "#f2ecd9"
      },
      {
        "id": "blue",
        "label": "Blue",
        "swatch": "#93b7d3"
      },
      {
        "id": "cyan",
        "label": "Cyan",
        "swatch": "#bfe6e1"
      },
      {
        "id": "darkgreen",
        "label": "Dark Green",
        "swatch": "#034539"
      }
    ]
  },
  {
    "slug": "sunburst-hardshell",
    "name": "Sunburst Hardshell",
    "blurb": "Radiating fan-pleat shell with the KIYO badge",
    "colours": [
      {
        "id": "black",
        "label": "Black",
        "swatch": "#36373a"
      },
      {
        "id": "beige",
        "label": "Beige",
        "swatch": "#d7b5a8"
      },
      {
        "id": "green",
        "label": "Green",
        "swatch": "#a6d1bf"
      },
      {
        "id": "pink",
        "label": "Pink",
        "swatch": "#e4a6a9"
      },
      {
        "id": "orange",
        "label": "Orange",
        "swatch": "#f8652c"
      }
    ]
  },
  {
    "slug": "front-pocket-cabin",
    "name": "Front Pocket Cabin",
    "blurb": "Full-width zipped laptop pocket",
    "colours": [
      {
        "id": "white",
        "label": "White",
        "swatch": "#dbdbdb"
      },
      {
        "id": "blue",
        "label": "Blue",
        "swatch": "#8abfd2"
      },
      {
        "id": "pink",
        "label": "Pink",
        "swatch": "#daafa9"
      }
    ]
  },
  {
    "slug": "top-access-cabin",
    "name": "Top Access Cabin",
    "blurb": "Separate upper compartment for quick access",
    "colours": [
      {
        "id": "white",
        "label": "White",
        "swatch": "#e5dac5"
      },
      {
        "id": "green",
        "label": "Green",
        "swatch": "#abc79e"
      },
      {
        "id": "purple",
        "label": "Purple",
        "swatch": "#c7a8c1"
      },
      {
        "id": "pink",
        "label": "Pink",
        "swatch": "#eaaf9a"
      }
    ]
  },
  {
    "slug": "mini-hard-case",
    "name": "Mini Hard Case",
    "blurb": "Top-handle vanity case with aluminium corners",
    "colours": [
      {
        "id": "black",
        "label": "Black",
        "swatch": "#2e2e30"
      },
      {
        "id": "blue",
        "label": "Blue",
        "swatch": "#b4d1ee"
      },
      {
        "id": "green",
        "label": "Green",
        "swatch": "#b7d4c1"
      },
      {
        "id": "purple",
        "label": "Purple",
        "swatch": "#bfb0ea"
      },
      {
        "id": "pink",
        "label": "Pink",
        "swatch": "#e6babd"
      }
    ]
  },
  {
    "slug": "business-backpack",
    "name": "Business Backpack",
    "blurb": "Structured commuter backpack",
    "colours": [
      {
        "id": "black",
        "label": "Black",
        "swatch": "#28282a"
      },
      {
        "id": "grey",
        "label": "Grey",
        "swatch": "#9da2af"
      }
    ]
  },
  {
    "slug": "flap-commuter-backpack",
    "name": "Flap Commuter Backpack",
    "blurb": "Flap-over front with a leather pull tag",
    "colours": [
      {
        "id": "black",
        "label": "Black",
        "swatch": "#2b2b2e"
      },
      {
        "id": "grey",
        "label": "Grey",
        "swatch": "#94949a"
      }
    ]
  },
  {
    "slug": "slim-laptop-brief",
    "name": "Slim Laptop Brief",
    "blurb": "Slim zip-top brief with rolled handles",
    "colours": [
      {
        "id": "black",
        "label": "Black",
        "swatch": "#2c2d2e"
      },
      {
        "id": "grey",
        "label": "Grey",
        "swatch": "#bababd"
      }
    ]
  },
  {
    "slug": "weekender-duffel",
    "name": "Weekender Duffel",
    "blurb": "Wide duffel with a detachable shoulder strap",
    "colours": [
      {
        "id": "black",
        "label": "Black",
        "swatch": "#38383a"
      },
      {
        "id": "grey",
        "label": "Grey",
        "swatch": "#9b9ca4"
      }
    ]
  }
];

export function productImage(slug: string, colour: string, view: "front" | "angle") {
  return `/images/kiyo/products/${slug}/${colour}-${view}.webp`;
}
