/* Generated by tools/build-section-assets.mjs. Do not edit by hand. */
/* Alt text is NOT here on purpose: it is authored in imageSlots.ts, where it
   can describe the picture rather than repeat a filename. */

export type SectionAsset = { src: string; width: number; height: number };

export const sectionAssets = {
  heroAirport: { src: "/images/kiyo/sections/heroAirport.webp", width: 1794, height: 877 },
  warehouseTruck: { src: "/images/kiyo/sections/warehouseTruck.webp", width: 1920, height: 800 },
  umrahBanner: { src: "/images/kiyo/sections/umrahBanner.webp", width: 1600, height: 781 },
  umrahSet1: { src: "/images/kiyo/sections/umrahSet1.webp", width: 1100, height: 758 },
  umrahSet2: { src: "/images/kiyo/sections/umrahSet2.webp", width: 1100, height: 758 },
  umrahSet3: { src: "/images/kiyo/sections/umrahSet3.webp", width: 1100, height: 758 },
  umrahSet4: { src: "/images/kiyo/sections/umrahSet4.webp", width: 1100, height: 758 },
  corporateBanner: { src: "/images/kiyo/sections/corporateBanner.webp", width: 1600, height: 781 },
  corporateSet1: { src: "/images/kiyo/sections/corporateSet1.webp", width: 1100, height: 825 },
  corporateSet2: { src: "/images/kiyo/sections/corporateSet2.webp", width: 1100, height: 825 },
  corporateSet3: { src: "/images/kiyo/sections/corporateSet3.webp", width: 1100, height: 825 },
  corporateSet4: { src: "/images/kiyo/sections/corporateSet4.webp", width: 1100, height: 825 },
  brandCase: { src: "/images/kiyo/sections/brandCase.webp", width: 1000, height: 1039 },
  brandDetail1: { src: "/images/kiyo/sections/brandDetail1.webp", width: 900, height: 900 },
  brandDetail2: { src: "/images/kiyo/sections/brandDetail2.webp", width: 900, height: 900 },
  brandDetail3: { src: "/images/kiyo/sections/brandDetail3.webp", width: 900, height: 900 },
  brandDetail4: { src: "/images/kiyo/sections/brandDetail4.webp", width: 900, height: 900 },
  brandDetail5: { src: "/images/kiyo/sections/brandDetail5.webp", width: 900, height: 900 },
  pipeline1: { src: "/images/kiyo/sections/pipeline1.webp", width: 800, height: 552 },
  pipeline2: { src: "/images/kiyo/sections/pipeline2.webp", width: 800, height: 551 },
  pipeline3: { src: "/images/kiyo/sections/pipeline3.webp", width: 800, height: 551 },
  pipeline4: { src: "/images/kiyo/sections/pipeline4.webp", width: 800, height: 551 },
  pipeline5: { src: "/images/kiyo/sections/pipeline5.webp", width: 800, height: 551 },
  pipeline6: { src: "/images/kiyo/sections/pipeline6.webp", width: 800, height: 551 },
  clientVideo: { src: "/images/kiyo/sections/clientVideo.webp", width: 1400, height: 788 },
  partnerCorporate: { src: "/images/kiyo/sections/partnerCorporate.webp", width: 800, height: 600 },
  partnerUmrah: { src: "/images/kiyo/sections/partnerUmrah.webp", width: 800, height: 600 },
  partnerWarehouse: { src: "/images/kiyo/sections/partnerWarehouse.webp", width: 800, height: 600 },
  samantha: { src: "/images/kiyo/sections/samantha.webp", width: 1000, height: 1333 },
  bookshelf: { src: "/images/kiyo/sections/bookshelf.webp", width: 1920, height: 800 },
  awardsRow1: { src: "/images/kiyo/sections/awardsRow1.webp", width: 1400, height: 217 },
  awardsRow2: { src: "/images/kiyo/sections/awardsRow2.webp", width: 1400, height: 210 },
  reachMapFallback: { src: "/images/kiyo/sections/reachMapFallback.webp", width: 1600, height: 699 },
} satisfies Record<string, SectionAsset>;

/** The client marks, in the order the wall shows them. */
export const clientLogoAssets: (SectionAsset & { id: string })[] = [
  { id: "clientLogoAia", src: "/images/kiyo/sections/logos/01-aia.webp", width: 480, height: 240 },
  { id: "clientLogoClientCrestGreen", src: "/images/kiyo/sections/logos/02-client-crest-green.webp", width: 480, height: 240 },
  { id: "clientLogoKoperasiTnb", src: "/images/kiyo/sections/logos/03-koperasi-tnb.webp", width: 480, height: 240 },
  { id: "clientLogoTabungPendidikan", src: "/images/kiyo/sections/logos/04-tabung-pendidikan.webp", width: 480, height: 240 },
  { id: "clientLogoClientCooperativeCrest", src: "/images/kiyo/sections/logos/05-client-cooperative-crest.webp", width: 480, height: 240 },
  { id: "clientLogoIirkaz", src: "/images/kiyo/sections/logos/06-iirkaz.webp", width: 480, height: 240 },
  { id: "clientLogoBigBath", src: "/images/kiyo/sections/logos/07-big-bath.webp", width: 480, height: 240 },
  { id: "clientLogoManipalUniversityCollegeMalaysia", src: "/images/kiyo/sections/logos/08-manipal-university-college-malaysia.webp", width: 480, height: 240 },
  { id: "clientLogoBerkatTuahTravelTours", src: "/images/kiyo/sections/logos/09-berkat-tuah-travel-tours.webp", width: 480, height: 240 },
  { id: "clientLogoJalen", src: "/images/kiyo/sections/logos/10-jalen.webp", width: 480, height: 240 },
  { id: "clientLogoBoldMedia", src: "/images/kiyo/sections/logos/11-bold-media.webp", width: 480, height: 240 },
  { id: "clientLogoUnikl", src: "/images/kiyo/sections/logos/12-unikl.webp", width: 480, height: 240 },
];

export const reachMapSvg = "/images/kiyo/sections/reachMap.svg";
