/* Generated by tools/build-section-assets.mjs. Do not edit by hand. */
/* Alt text is NOT here on purpose: it is authored in imageSlots.ts, where it
   can describe the picture rather than repeat a filename. */

export type SectionAsset = { src: string; width: number; height: number };

export const sectionAssets = {
  heroHome: { src: "/images/kiyo/sections/heroHome.webp", width: 1794, height: 877 },
  warehouseTruck: { src: "/images/kiyo/sections/warehouseTruck.webp", width: 1920, height: 800 },
  umrahOpener: { src: "/images/kiyo/sections/umrahOpener.webp", width: 1795, height: 876 },
  umrahSet1: { src: "/images/kiyo/sections/umrahSet1.webp", width: 1200, height: 800 },
  umrahSet2: { src: "/images/kiyo/sections/umrahSet2.webp", width: 1200, height: 800 },
  umrahSet3: { src: "/images/kiyo/sections/umrahSet3.webp", width: 1200, height: 800 },
  umrahSet4: { src: "/images/kiyo/sections/umrahSet4.webp", width: 1200, height: 800 },
  umrahSet5: { src: "/images/kiyo/sections/umrahSet5.webp", width: 1200, height: 800 },
  umrahSet6: { src: "/images/kiyo/sections/umrahSet6.webp", width: 1200, height: 800 },
  corporateOpener: { src: "/images/kiyo/sections/corporateOpener.webp", width: 1774, height: 887 },
  corporateSet1: { src: "/images/kiyo/sections/corporateSet1.webp", width: 1100, height: 825 },
  corporateSet2: { src: "/images/kiyo/sections/corporateSet2.webp", width: 1100, height: 825 },
  corporateSet3: { src: "/images/kiyo/sections/corporateSet3.webp", width: 1100, height: 825 },
  corporateSet4: { src: "/images/kiyo/sections/corporateSet4.webp", width: 1100, height: 825 },
  corporateSet5: { src: "/images/kiyo/sections/corporateSet5.webp", width: 1100, height: 825 },
  chooseOpener: { src: "/images/kiyo/sections/chooseOpener.webp", width: 1792, height: 896 },
  personaliseOpener: { src: "/images/kiyo/sections/personaliseOpener.webp", width: 1774, height: 887 },
  brandDetail1: { src: "/images/kiyo/sections/brandDetail1.webp", width: 1000, height: 1000 },
  brandDetail2: { src: "/images/kiyo/sections/brandDetail2.webp", width: 700, height: 700 },
  brandDetail3: { src: "/images/kiyo/sections/brandDetail3.webp", width: 700, height: 700 },
  brandDetail4: { src: "/images/kiyo/sections/brandDetail4.webp", width: 700, height: 700 },
  brandMockup: { src: "/images/kiyo/sections/brandMockup.webp", width: 900, height: 620 },
  deliverOpener: { src: "/images/kiyo/sections/deliverOpener.webp", width: 1792, height: 896 },
  deliverShip: { src: "/images/kiyo/sections/deliverShip.webp", width: 1400, height: 965 },
  deliverStore: { src: "/images/kiyo/sections/deliverStore.webp", width: 1600, height: 900 },
  deliverCollect: { src: "/images/kiyo/sections/deliverCollect.webp", width: 1600, height: 960 },
  clientsOpener: { src: "/images/kiyo/sections/clientsOpener.webp", width: 1792, height: 896 },
  aboutBand: { src: "/images/kiyo/sections/aboutBand.webp", width: 1920, height: 800 },
} satisfies Record<string, SectionAsset>;

/** The client marks, in the order the wall shows them. */
export const clientLogoAssets: (SectionAsset & { id: string })[] = [
  { id: "clientLogoAia", src: "/images/kiyo/sections/logos/01-aia.webp", width: 480, height: 240 },
  { id: "clientLogoClientCrestGreen", src: "/images/kiyo/sections/logos/02-client-crest-green.webp", width: 480, height: 240 },
  { id: "clientLogoKoperasiTnb", src: "/images/kiyo/sections/logos/03-koperasi-tnb.webp", width: 480, height: 240 },
  { id: "clientLogoTabungPendidikan", src: "/images/kiyo/sections/logos/04-tabung-pendidikan.webp", width: 480, height: 240 },
  { id: "clientLogoClientCooperativeCrest", src: "/images/kiyo/sections/logos/05-client-cooperative-crest.webp", width: 480, height: 240 },
  { id: "clientLogoIirkaz", src: "/images/kiyo/sections/logos/06-iirkaz.webp", width: 480, height: 240 },
  { id: "clientLogoBigBath", src: "/images/kiyo/sections/logos/07-big-bath.webp", width: 480, height: 240 },
  { id: "clientLogoManipalUniversityCollegeMalaysia", src: "/images/kiyo/sections/logos/08-manipal-university-college-malaysia.webp", width: 480, height: 240 },
  { id: "clientLogoBerkatTuahTravelTours", src: "/images/kiyo/sections/logos/09-berkat-tuah-travel-tours.webp", width: 480, height: 240 },
  { id: "clientLogoJalen", src: "/images/kiyo/sections/logos/10-jalen.webp", width: 480, height: 240 },
  { id: "clientLogoBoldMedia", src: "/images/kiyo/sections/logos/11-bold-media.webp", width: 480, height: 240 },
  { id: "clientLogoUnikl", src: "/images/kiyo/sections/logos/12-unikl.webp", width: 480, height: 240 },
];
