/**
 * Self-host the two web fonts the design uses.
 *
 * `app/fonts.ts` declares Cormorant Garamond and Montserrat through
 * `next/font/google`, which downloads them into `.vinext/fonts`. The Vinext
 * build then never emits the `@font-face` rules or the CSS variable class that
 * go with them, so every heading silently fell back to a system serif. Rather
 * than depend on that integration, this copies the same faces into
 * `public/fonts` and writes plain `@font-face` rules any host can serve.
 *
 * The families and weights here must stay in step with `app/fonts.ts`.
 *
 * Only the latin and latin-ext subsets are kept: the site is English and Malay,
 * and shipping Cyrillic and Vietnamese would triple the font payload for
 * nothing.
 *
 *   node tools/build-fonts.mjs
 */

import { copyFile, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { basename } from "node:path";

const CACHE = new URL("../.vinext/fonts/", import.meta.url);
const PUBLIC = new URL("../public/fonts/", import.meta.url);
const OUT = new URL("../app/fonts.css", import.meta.url);

const WANTED = [
  { prefix: "cormorant-garamond-", family: "Cormorant Garamond", weights: ["500", "600"] },
  { prefix: "montserrat-", family: "Montserrat", weights: ["400", "500", "600", "700"] },
];

const KEEP_SUBSETS = ["latin", "latin-ext"];

/** Split a style.css into `{ subset, block }` pairs. */
function faces(css) {
  const out = [];
  const pattern = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let match;
  while ((match = pattern.exec(css)) !== null) out.push({ subset: match[1], block: match[2] });
  return out;
}

const read = (block, property) => new RegExp(`${property}:\\s*([^;]+);`).exec(block)?.[1].trim();

await mkdir(PUBLIC, { recursive: true });

const directories = await readdir(CACHE);
const rules = [];

for (const { prefix, family, weights } of WANTED) {
  const directory = directories.find((entry) => entry.startsWith(prefix));
  if (!directory) throw new Error(`No cached download for ${family}. Run a build once with network access first.`);

  const css = await readFile(new URL(`${directory}/style.css`, CACHE), "utf8");

  for (const { subset, block } of faces(css)) {
    if (!KEEP_SUBSETS.includes(subset)) continue;

    const weight = read(block, "font-weight");
    if (!weight || !weights.includes(weight)) continue;

    const source = /url\(([^)]+)\)/.exec(block)?.[1];
    if (!source) continue;
    const file = basename(source);

    await copyFile(new URL(`${directory}/${file}`, CACHE), new URL(file, PUBLIC));

    rules.push(
      [
        `/* ${family} ${weight}, ${subset} */`,
        "@font-face {",
        `  font-family: "${family}";`,
        "  font-style: normal;",
        `  font-weight: ${weight};`,
        "  font-display: swap;",
        `  src: url("/fonts/${file}") format("woff2");`,
        `  unicode-range: ${read(block, "unicode-range")};`,
        "}",
      ].join("\n"),
    );
  }
}

const header = [
  "/* Generated by tools/build-fonts.mjs. Do not edit by hand. */",
  "/* Faces are served from public/fonts, so no third-party request is made at",
  "   runtime and the build needs no network access. */",
  "",
].join("\n");

await writeFile(OUT, `${header}${rules.join("\n\n")}\n`);
console.log(`wrote ${rules.length} @font-face rules to app/fonts.css`);
